config:
    target: "http://localhost:3000"
    phases:
        - duration: 60
          arrivalRate: 1
          name: "Send all records"
    engines:
        socketio: {}
    processor: "./build/payloadProcessor.js"

scenarios:
    - name: "Emit xlsx data"
      engine: "socketio"
      flow:
          - loop:
                - function: "generatePayload"
                - emit:
                      channel: "message"
                      data: "{{ payload }}"
                - think: 1
            count: 10000
