config:
    target: "http://localhost:3000"
    phases:
        - duration: 3600
          arrivalRate: 14
          name: "Load Test for 1 hour with over 50000 clients creating 14 clients per second"
    engines:
        socketio: {}
    processor: "./build/payloadProcessor.js"

scenarios:
    - name: "Emit xlsx data"
      engine: "socketio"
      flow:
          - loop:
                - function: "generatePayload"
                - emit:
                      channel: "message"
                      data: "{{ payload }}"
                - think: 5
            count: 720
