config:
    target: "http://localhost:3000"
    phases:
        - duration: 60
          arrivalRate: 1
          rampTo: 3
          name: "Ramping up the load"
    engines:
        socketio: {}
    processor: "./build/payloadProcessor.js"

scenarios:
    - name: "Emit xlsx data"
      engine: "socketio"
      flow:
          - loop:
                - emit:
                      channel: "message"
                      data: "Hello from Artillery!"
                  response:
                      on: "onResponse"
                - think: 5
            count: 3
