config:
    target: "ws://127.0.0.1:57200"
    phases:
        - duration: 3600
          arrivalRate: 14
          rampTo: 50
          name: "Load Test for 1 hour targeting around 50,000 clients"
    engines:
        socketio: {}
    processor: "./build/payloadProcessor.js"

scenarios:
    - name: "Emit xlsx data"
      engine: "socketio"
      socketio:
          transports: ["websocket"]
      flow:
          - loop:
                - function: "generatePayload"
                - emit:
                      channel: "message"
                      data: "{{ payload }}"
                - think: 5
            count: 720
