apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: websocket-server-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: websocket-server
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
