apiVersion: v1
kind: Service
metadata:
    name: websocket-service
spec:
    type: LoadBalancer
    selector:
        app: websocket
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
